sudo: required

services:
  - docker

before_install:
  - docker build -t pianisimo/docker-workflow .
script:
  - ls
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "workflow-test"
  env: "Workflowtest-env"
  bucket_name: "elasticbeanstalk-us-east-2-771866977691"
  bucket_path: "workflow-test"
  on:
    branch: master
  access_key_id: $Access_key_ID
  secret_access_key: $Secret_access_key
