sudo: required

services:
  - docker

before_install:
  - docker build -t pianisimo/docker-workflow -f Dockerfile.dev .
#script:
#  -
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-workflow"
  env: "Dockerworkflow-env"
  bucket_name: "elasticbeanstalk-us-east-2-771866977691"
  bucket_path: "docker-workflow"
  on:
    branch: master
  access_key_id: "$Access key ID"
  secret_access_key:
    secure: "$Secret Access Key"
